singularity-energy/open-grid-emissions

- src/data_cleaning.py
- src/data_pipeline.py
At some point, it looks like an argument was added to `data_cleaning.combine_plant_data()` to allow the user to not validate that the data being combined does not overlap. For some reason, the default argument was set to `False`, which means that the combined hourly data was not being validated for potential overlaps. This PR fixes that by changing the default argument to `True`
> Validate that data does not overlap when combining

- src/data_pipeline.py
- src/load_data.py
Closes https://github.com/singularity-energy/open-grid-emissions/issues/243 by using v0.3 of the EPA's Power Sector Data Crosswalk.
> Integrate Power Sector Data Crosswalk v0.3

- README.md
- notebooks/explore_data/explore_intermediate_outputs.ipynb
- src/column_checks.py
- src/emissions.py
- src/load_data.py
- test/test_load_data.py
This PR is meant to address https://github.com/singularity-energy/open-grid-emissions/issues/255.
To get around the fact that some NOx and SO2 control data doesn't have an associated nox or so2 control id, we now load all four control ids (nox, so2, pm, hg) and use these to map the data to a boiler if the nox or so2 id is missing. 
Previously we had dropped all rows from the air emissions control table that had a missing pollutant-specific control id, but now we only drop rows that don't have any pollutant-specific data (ie if we're calculating nox, we drop any rows that don't have any nox control data.
I've set this up as an iterative process where the user specifies which id they want to use as primary, and then the code cycles through each additional id, filling missing boiler …
> Fix missing NOx and SO2 identifiers

- environment.yml
- src/consumed.py
- src/eia930.py
Fix missing values by running check for non-zero export with zero generation: check now happens *after* converting nan to 0. 
Make 930 usage consistent with residual calculation by rounding values < 1.5 to 0; this gets rid of 1 values added by `gridemissions`.
> Fix consumed calc

- data/manual/plants_not_connected_to_grid.csv
- notebooks/validation/validate_vs_egrid.ipynb
- src/data_cleaning.py
- src/data_pipeline.py
- src/load_data.py
- test/test_download_data.py
- Adds eGRID 2021 data to our list of downloads
- Updates the list of non-grid connected plants based on additions to the list in eGRID 2021.
- Fixes an issue where a plant with no reported ba_code was getting filled with the incorrect code based on the ba_name. 
In comparing our 2021 data to the eGRID 2021 data, I found that there are some plants that EIA-860 identifies as being in ISNE that are getting assigned to NYIS by pudl, and thus are categorized in a different BA than they are in eGRID. All of these plants seem to be physically located in the state of New York, but are listed with an ISNE BA code. Also, all of these plants are pretty small. See: https://github.com/catalyst-cooperative/pudl/issues/2255. For now, I was going to leave this in place until this is resolved on the pudl …
> add eGRID2021 data

- src/data_cleaning.py
- src/validation.py
`validation.check_allocated_gf_matches_input_gf()` checks that the allocated generation and fuel from EIA-923 matches the input totals when running `data_cleaning.clean_eia923()`. 
Changes in this PR:
- Previously, we had flagged differences that were greater than an absolute threshold arbitrarily set at 10 units. We now flag allocated totals that are more than +/- 0.1% different than the input total. This threshold is in place so that values that are off by very small amounts due to rounding errors are not flagged.
- We add more helpful warning messages that shows the percentage difference, input total, and allocated total for easy comparison
Note: this validation check should be temporary until https://github.com/catalyst-cooperative/pudl/pull/2297 and …
> Update the flag threshold in `Check_allocated_gf_matches_input_gf`

- .gitignore
- environment.yml
- src/__init__.py
- src/column_checks.py
- src/consumed.py
- src/data_cleaning.py
- src/data_pipeline.py
- src/download_data.py
- src/eia930.py
- src/emissions.py
- src/filepaths.py
- src/gross_to_net_generation.py
- src/impute_hourly_profiles.py
- src/load_data.py
- src/logging_util.py
- src/output_data.py
- src/validation.py
- src/visualization.py
- test/test_logging.py
This PR configures logging in `logging_util.py` such that:
- PUDL logging messages are not hidden
- OGE logging messages are formatted similar to PUDL (see below)
- All logging messages from the data pipeline (including PUDL and other imports) are directed to a logfile (`data/outputs/data_pipeline.log`). The logfile could easily be changed to a different filepath.
Here's an example of running the data pipeline with the new logging system:
**Note:**
Unfortunately, if you just do `logger.info(df)`, the header won't line up well with the data. So I replaced all of the dataframe printouts to be `logger.info("\n" + df.to_string())`, which will make everything look nice.
> Make PUDL logging show up, and set up logging in OGE

- src/consumed.py
- src/download_data.py
- src/validation.py
This finishes up the work started in https://github.com/singularity-energy/open-grid-emissions/pull/285, converting a few more print statements that we did not originally catch to logger.info or logger.warning.
> Finish logger conversion

- src/data_pipeline.py
- src/filepaths.py
- src/logging_util.py
I was originally debugging the `--small` option for the data pipeline, which crashes at the EIA-930 cleaning step. During that process, I made a couple improvements to how command line arguments are handled in `data_pipeline.py`:
- Boolean flags like `--small`, `--flat`, and `--skip_outputs` don't need a value after them any more. If you omit these arguments, the default is used. If you include `--small`, that value will be true. This is to be more consistent with other command line interfaces.
- I added a step to print out the command line arguments that are being used, so that they're clearly shown to the user and captured in the logs.
EDIT: Added one more change to this PR:
- If the logger is outputting to a file, makes sure that the directory for that file exists (otherwise an error …
> Small improvements to command line arguments

- src/data_cleaning.py
- src/data_pipeline.py
- src/download_data.py
- src/eia930.py
- src/gross_to_net_generation.py
- src/impute_hourly_profiles.py
- src/load_data.py
- src/logging_util.py
- src/output_data.py
- src/validation.py
Currently, the pipeline outputs the log file to `outputs_folder("data_pipeline.log")`, but it would be better if the log were saved to the directory for the specific year for which the pipeline was run, e.g. `outputs_folder("{year}/data_pipeline.log")`. However, the root logger is configured outside of `main()` where the year was defined. To get around this, I just made the final step of the data pipeline `shutil.move(outputs_folder("data_pipeline.log"), outputs_folder(f"{year}/data_pipeline.log"))`. However, I'm not sure if this is a good way to do this. @miloknowles would there be a better / easy way to write directly to the specific year folder?
This PR also makes a few small formatting changes:
- formats `logging_util.py` using black
- Removes the indent from all logging messages
> Small logging updates

- src/data_cleaning.py
- src/gross_to_net_generation.py
- src/impute_hourly_profiles.py
- src/load_data.py
- src/output_data.py
- src/validation.py
This PR includes a series of improvements to address many of the small/easy validation coverage tasks. Fixes CAR-1878, CAR-1877, CAR-1876, CAR-1875, CAR-1872, CAR-1867, CAR-1866. 
Specifically, this PR does the following:
1. Expand the coverage of `validate_unique_datetimes` to check whenever we are loading hourly data inputs, concat-ing hourly dataframes together, and outputting hourly data. (This does not yet check the datetimes in EIA-930 data)
2. Expand the coverage of `validate_shaped_totals`. Previously we had been running this check separately from `impute_hourly_profiles.shape_monthly_eia_data_as_hourly()`. We now embed this check within that function so that it has to be run after shaping.
3. I checked that `ensure_non_overlapping_data_from_all_sources` was being run every time …
> Expand validation of outputs

- src/data_pipeline.py
For transparency, I wanted to propose that we change the location of the data pipeline log file from our outputs folder (which gets archived on Zenodo) to the `data_quality_metrics` directory, which users can download directly from the data download page.  This will help give data users transparency into the options, steps, and warnings associated with the data pipeline, if they choose to take a look at this. 
I also realized that we were specifying the location of the logfile before we created all of the sub directories, so I moved the logfile configuration to after the initial code that creates the directory structure.
> Change logfile location to data quality metrics results

- src/eia930.py
CAISO had previously been reporting start-of-hour values to EIA-930, instead of end-of-hour, as instructed, so we had been applying a timestamp correction to shift the values by +1 hours. However, it looks like starting on June 16, 2022, CAISO started correctly reporting end-of-hour values, so we want to end the correction on this date.
Since we have not yet published 2022 OGE data, this should not affect any of our current outputs.
> Fix CAISO timestamp correction

- src/column_checks.py
- src/data_cleaning.py
- src/data_pipeline.py
- src/validation.py
This PR fixes CAR-1909.
Combined cycle generators contain a steam part (CA) and turbine part (CT) that are linked together. Thus, our subplant groups that contain one part of a combined cycle plant should always in theory contain the other part as well. This PR adds a test that checks that both parts exist in a subplant if one exists.
Besides CT and CA prime movers, there is also CS prime movers which represent a "single shaft" combined cycle unit where the steam and turbine parts share a single generator. These prime movers are allowed to be by themselves in a subplant, as are CC prime movers, which represent a "total unit."
This PR adds a `prime_mover_code` column to the subplant crosswalk table to help validating this.  
This PR also updates the code to export the subplant crosswalk …
> Validate subplants have both combined cycle parts

- Pipfile
- Pipfile.lock
- README.md
- environment.yml
- pyproject.toml
- src/oge/data_pipeline.py
- src/oge/eia930.py
- src/oge/filepaths.py
Allow users to read OGE output data from Amazon S3. This is particularly useful when we want to use OGE outputs in a separate project. Closes CAR-3681
Create a function setting the OGE data store. It is looking for an `OGE_DATA_STORE` environment variable. If it does not exist the data store is set to local and it will write/read data to/from the **open_grud_emissions_data** folder located in the users' **$HOME** (current behavior)
The feature has been tested setting the `OGE_DATA_DIR` environment variable to `s3` in a project importing the `oge` package. A file stored on Amazon S3 was then successfully loaded using the `pandas`' `read_csv` function
* **Pipfile** and **environment.yml** where I have added the `s3fs` dependency as it is needed by pandas to read files located on Amazon S3. …
> Access OGE outputs from Amazon S3

- README.md
- src/oge/constants.py
- src/oge/consumed.py
- src/oge/data_cleaning.py
- src/oge/data_pipeline.py
- src/oge/emissions.py
- src/oge/load_data.py
- src/oge/output_data.py
- src/oge/validation.py
Some of the changes implemented in https://github.com/singularity-energy/open-grid-emissions/pull/337 introduced a circular import between the `load_data` and `emissions` modules, due to the import of `CLEAN_FUELS` into the `load_data` module. 
Moves `CLEAN_FUELS` (along with some other constants) to a new `constants.py` module to prevent a circular import. 
While in the process of fixing this specific circular import, I also searched the repo for where other constants / assumptions were specified and consolidated them into `constants`.
In `emissions.calculate_electric_allocation_factor()` updated the calculation steps and column names to match the process described in the "Adjusting Emissions for CHP" docs (there is no methodological change here, just separating out several steps and …
> Fix circular import of CLEAN_FUELS and add constants

- src/oge/filepaths.py
When importing OGE into another module on windows, and attempting to load data from s3, the current way filepaths are handled results in a FileNotFound error.
For example, running `oge.filepaths.results_folder("2022/plant_data/plant_static_attributes.csv")` returns:
```
's3://open-grid-emissions/open_grid_emissions_data\\results\\2022/plant_data/plant_static_attributes.csv'
```
Where `os.path.join()` is concatting parts of the filepath together, it is adding a "\\" rather than a "/".
When attempting to read from this location, for example using `pd.read_csv(oge.filepaths.results_folder("2022/plant_data/plant_static_attributes.csv")`, this results in:
```
FileNotFoundError: open-grid-emissions/open_grid_emissions_data\results\2022/plant_data/plant_static_attributes.csv
```
Here, the mix of …
> Fix filepaths for s3

- notebooks/validation/validate_subplant_crosswalk.ipynb
Compare mapping of (`plant_id_eia`, `generator_id`) to `subplant_id` across years. Closes CAR-3518
Load the sub-plant crosswalk files for years 2019 through 2022. For each year combination, the intersection of (`plant_id_eia`, `generator_id`) is retrieved and occurrences where the `subplant_id` values differ are saved as a `pandas` data frame.
N/A
A new notebook named `validate_subplant_crosswalk` encloses this short analysis
See notebook outputs [here](https://github.com/singularity-energy/open-grid-emissions/blob/ben/crosswalk/notebooks/validation/validate_subplant_crosswalk.ipynb), e.g.,
```
Number of difference in subplant_id for same (plant_id_eia, generator_id) combination
2019-2020: 448
2019-2021: 895
2019-2022: 1193
2020-2021: 488
2020-2022: 831
2021-2022: 435
```
10min
N/A
> Create notebook looking at subplant id across years

- src/oge/emissions.py
Allow to calculate a CO2 mass equivalent value using a Global Warming Potential (GWP) value published in any available IPCC's assessment report (AR).
Modify the `calculate_co2e_mass` function such that its second parameter can be used to fetch not only the most recent AR that was available in the given year as done previously but also to directly fetch the AR.
Tested manually
In the `oge.emissions` module
```python
>>> import pandas as pd
>>> from emissions import calculate_co2e_mass
>>> calculate_co2e_mass(pd.DataFrame(), "AR32")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/brdo/Singularity/open-grid-emissions/src/oge/emissions.py", line 418, in calculate_co2e_mass
raise ValueError(
ValueError: version must be a year in [1995, 2021] or a valid AR …
```
> Access a specific GWP when calculating CO2 mass equivalent value

- README.md
- notebooks/validation/anomaly_screening.ipynb
- src/oge/anomaly_screening.py
- src/oge/data_cleaning.py
- src/oge/validation.py
Screen timeseries for anomalous value following the algorithm steps described in Tyler H. Ruggles et al. *Developing reliable hourly electricity demand data through screening and imputation* (2020). Closes CAR-1882.
Note that the screening algorithms have been developed for demand time series and some of these algorithms might not be tailored for generation/emission time series.
The screening is conducted in 2 steps. Step 1 removes the most egregious anomalies where few or no calculations are needed. Afterward, in Step 2, the most extreme values have been removed making calculations of local characteristics of the data more reasonable. Through this screening process hourly values can be re-categorized from okay to other classifications based on the algorithms.
Implement the screening …
> Implement data anomaly screening described in Ruggles et al.

- src/oge/data_pipeline.py
In https://github.com/singularity-energy/open-grid-emissions/pull/353, we required that the subplant identification code load raw EIA-860 data from the latest validated year (2022). However, if running the pipeline for the first time for any year other than the latest validated year, this would lead to an error, since that file is not downloaded. This PR adds code to download the EIA-860 file for the latest validated year. 
Fixed CAR-3907
See data_pipeline.py
Ran the download part of the data pipeline for 2019. 
See data_pipeline.py
1 min
What issues were identified that are not being addressed in this PR but should be addressed in future work?
> Get EIA-860 data from latest validated year

- src/oge/constants.py
- src/oge/data_cleaning.py
- src/oge/data_pipeline.py
- src/oge/download_data.py
- src/oge/output_data.py
- src/oge/validation.py
This PR updates the data pipeline to allow for the creation of historical data from 2013-2018. Because EIA-930 data is not available for a complete year prior to 2019, the data outputs prior to that year will be limited to the following:
- Only monthly and annual-resolution data will be available (no hourly data) - we could potentially still include hourly data for the plants that report to CEMS.
- Only generated data will be available since interchange data from EIA-930 is not available.
Most of the updates are in `data_pipeline.py` with minor changes in other files to update allowed year ranges, and update certain functions to accept an argument to specify different behavior based on whether hourly data is available or not.
Document in more depth the changes being made
A couple …
> Expand historical coverage pre-2019

- src/oge/download_data.py
- src/oge/load_data.py
- src/oge/reference_tables/emission_factors_for_co2_ch4_n2o.csv
- src/oge/reference_tables/energy_source_groups.csv
Allow to run pipeline for years 2005, 2006 and 2007. Closes CAR-4211.
Add missing typehints and add/format docstrings in all functions located in the `load_data` and `download_data` modules.
* Print a warning message and return `download_data.download_raw_eia923` instead of raising an error for years < 2008
* Updates reference tables to add the `SC` energy source code that is used for years < 2008 in place of `SGC`
Run 2005, 2006 and 2007 pipelines successfully.
* the `download_data.download_raw_eia923` where we warn the file is not available and return
* the `load_data.load_pudl_table` where a warning is added if the table is empty
* the 2 reference tables (CSV files) where we added information for the `SC` energy code. 
From log file:
```
2024-05-17 11:21:37,194 [WARNING] …
```
> Add 2005, 2006 and 2007 years

- src/oge/column_checks.py
- src/oge/data_pipeline.py
- src/oge/helpers.py
- src/oge/load_data.py
Add the following fields to the plant static attributes: "latitude", "longitude", "county", "city", "zip_code", "street_address" and "capacity_mw". Closes CAR-4208.
Add missing typehints and add/format docstrings in modules that were edited.
* Create a function to load the geographical information of the plants from the raw EIA-860 data
* Load the `plants_entity_eia` PUDL table to retrieve the geographical information of the plants
* Supplement the PUDL table with data from the raw EIA-860 when entries are missing
* Output the plant static attributes file to disk for years < 2019
Successfully ran the 2010 pipeline.
The `oge.load_data` module where the new function load the geographical information from the raw EIA-860 and the `oge.helpers` module where fields to the plant static …
> Add geographical information to the plant static attributes data frame

- src/oge/column_checks.py
- src/oge/helpers.py
Add operating and retirement dates to plant static attributes.
A bug is fixed when calculating the nameplate capacity at the plant level
This PR also fixes an issue for years < 2013 where missing BA codes were being assigned, resulting in inaccurate BA-level results.
Create a new function that adds the operating and retirement dates of a plant to the plant static attributes data frame. The operating date of a plant is taken as the earliest date among all generators' operating date over all report dates. Likewise, the retirement date of a plant is taken as the latest date among all generators' retirement date over all report dates.
Successfully ran the 2013 pipeline. 
* the new `add_plant_operating_and_retirement_dates` in the `oge.helpers` module.
* the `oge.column_checks` module where …
> Add operating and retirement dates to plant static attributes

- src/oge/output_data.py
Fix function that calculates the averages of the fuel types. Closes CAR-4205.
Add a new row that summarizes all fuel categories as follows:
* Calculate the overall generated emission rates as $\frac{\sum_f E_f}{\sum_f G_f}$, where $E_f$ is the absolute emission of fuel $f$ and $G_f$ is the corresponding net generation
* Take the average of the non-rate columns
* Use `average` as fuel category for this new summarized row. 
Ran the 2005 pipeline
Relevant changes are in the the `write_generated_averages` function. Other edits add typehints and docstrings to function in the `oge.output_data` module.
N/A
5min
N/A
> Fix function calculating averages of the fuel types

- src/oge/reference_tables/emission_factors_for_co2_ch4_n2o.csv
In https://github.com/singularity-energy/open-grid-emissions/pull/374, I updated the energy_source_group reference table, but did not update the names of the fuels in the CO2 table, or add factors for the "SG" fuel type. This small PR adds those.
> update co2 factors based on manual energy source group updates

- pyproject.toml
In https://github.com/singularity-energy/open-grid-emissions/pull/368 we added `geopy` as a dependency to OGE, but this dependency was not updated in the `pyproject.toml` file, which means that certain modules are unusable if imported into another repo. This PR adds this dependency.
> Add geopy to pyproject dependencies

- notebooks/explore_data/compare_plant_coordinates.ipynb
Compare plants coordinates from PUDL and EIA-860. Closes CAR-4443. 
Outputs from notebook will be cleared after review
* Load plants entity in PUDL and EIA-860
* Get plants available in both dataset
* Calculate for each plant the angular distance between its coordinates from PUDL and EIA-860
N/A
Scroll through the notebook
5min
Look at plants with large angular separation
> Compare plants coordinates from PUDL and EIA-860

- src/oge/constants.py
- src/oge/data_pipeline.py
- src/oge/load_data.py
- src/oge/validation.py
Update the function validating the year when running the pipeline. Closes CAR-4450
Raise an exception if year passed to the `validate_year` function is not within `earliest_data_year` and `latest_validated_year`
```log
2024-07-19 16:10:11 [INFO] oge.data_pipeline:83 
Running with the following options:
* year = 2000
* shape_individual_plants = True
* small = False
* flat = False
* skip_outputs = False
2024-07-19 16:10:11 [INFO] oge.data_pipeline:136 Running data pipeline for year 2000
Traceback (most recent call last):
File "/Users/brdo/Singularity/open-grid-emissions/src/oge/data_pipeline.py", line 713, in <module>
main(sys.argv[1:])
File "/Users/brdo/Singularity/open-grid-emissions/src/oge/data_pipeline.py", line 137, in main
validation.validate_year(year)
File …
```
> Update warning message about validated years

- src/oge/helpers.py
Fix bug where nameplate capacity of non-operational generators were considered in the calculation of the nameplate capacity. Closes CAR-4479
Add a condition on the operational status.
Compared nameplate capacity of plants 113, 117 and 2442 that were flagged with a wrong nameplate capacity before changes. 
Very few changes.
N/A
2min
N/A
> Discard non-operational generators when calculating plant capacity

- Pipfile.lock
- environment.yml
- pyproject.toml
- src/oge/filepaths.py
Updates the version to 0.5.0. 
In s3, we will also begin saving versioned OGE data for the current and most recent data version. This data will now be saved in a directory with the version number, like `s3://open-grid-emissions/open_grid_emissions_data/v0.5.0`. Thus, I updated the filepath handler to use this convention for the code going forward.
I also updated the pipfile.lock to address all of the dependabot issues.
Updates the conda environment.yml file
Closes CAR-4491, CAR-4451, CAR-4466, CAR-4439
Points to correct location:
5 min
> Update to 0.5.0 and change s3 directory

- src/oge/reference_tables/epa_eia_crosswalk_manual.csv
Generators CTG3, CTG4, STG2, and PV1 were proposed to be added to the Riverside Energy Center (Plant 55641) and were in testing as of 2019 with scheduled COD in 2020. However, starting in the 2020 EIA data, these generators disappeared from this plant, and reappeared as the West Riverside Energy Center (Plant 64020). Closes CAR-4543.
2019 Proposed Generator Data:
2020 Operational Generator Data:
I've updated the manual EPA-EIA crosswalk file to represent this. STG2 does not appear to directly show up in the data
We would expect the subplant crosswalk to reflect the new mapping.
As expected, the EPA 55641 is no longer associated with those two units at EIA 55641 (although they still appear in the crosswalk, which is strange since they were never built)
These two units are now associated …
> Update EPA/EIA crosswalk of plant 55641

- src/oge/constants.py
- src/oge/load_data.py
This is a small PR that just does the minimum updates to download 2023 data and run the pipeline, without actually fixing any data quality issues yet. The pipeline did successfully complete but there are a number or errors raised, including a large amount of negative fuel in MISO. It is possible that these will be fixed once we properly go through the entire update process.
Advances CAR-4691
How is the purpose executed?
Ran the pipeline
* It's helpful to clarify where your new code lives if you moved files around or there could be confusion/
* What files are most important?
How the code can be used and/or images of any graphs, tables or other visuals (not always applicable).
5 minutes
The data pipeline log file was over 300MB because it output a large amount of hourly data in the warning. …
> Update year to 2023

- src/oge/reference_tables/energy_source_groups.csv
Remove extra comma in a CSV that was adding an extra empty field and in turn pandas' `read_csv` to fail
NA
N/A
The **src/oge/reference_tables/energy_source_groups.csv** file
N/A
1min
N/A
> Remove extra comma in energy source groups csv file

- src/oge/data_cleaning.py
- src/oge/eia930.py
- src/oge/reference_tables/epa_eia_crosswalk_manual.csv
- src/oge/reference_tables/temporary_primary_fuel_manual.csv
When running the 2023 pipeline, I encountered the following error:
```
2024-12-02 11:57:59 [INFO] oge.data_pipeline:370 11. Exporting monthly and annual plant-level results
2024-12-02 11:58:32 [WARNING] oge.oge.helpers:328                                                 net_generation_mwh
plant_id_eia subplant_id ba_code fuel_category                    
3            9           SOCO    <NA>                 2.744806e+05
47           17          TVA     <NA>                 3.646287e+04
18          TVA     <NA>                 4.581131e+04
19          TVA     <NA>                 4.091488e+04
56           5           SOCO    <NA>                 1.702325e+06
136          4           SEC     <NA>                 2.810318e+06
5           SEC     <NA>                 2.827317e+06
492 …
```
> Expand EPA-EIA crosswalk manual table and create primary fuel manual table

- notebooks/manual_data/update_steam_units_to_remove.ipynb
- src/oge/data_cleaning.py
- src/oge/data_pipeline.py
- src/oge/emissions.py
- src/oge/gross_to_net_generation.py
- src/oge/helpers.py
- src/oge/impute_hourly_profiles.py
- src/oge/load_data.py
- src/oge/reference_tables/epa_eia_crosswalk_manual.csv
- src/oge/validation.py
This PR addresses several warnings that were being raised in the 2023 data pipeline:
- When flagging differences between the inputs and outputs of the EIA-923 allocation process, update threshold to only warn if differences are greater than 0.01% to avoid warnings for rounding errors.
- Add a multi-year backstop for sulfur content so that we have complete sulfur content data for JF fuels
- Drop bad generators from the EIA-923 pipeline that were introduced by https://github.com/catalyst-cooperative/pudl/issues/3987
- Fix issue with missing fuel data for a plant that had recently retired, so wasn't appearing in the primary fuel table even though it was still reporting CEMS data
- Flag and drop CEMS units that report steam-only output and are not mapped to an EIA ID. These are likely for …
> Clean up warnings for 2023 data pipeline

- src/oge/consumed.py
- src/oge/data_pipeline.py
- src/oge/output_data.py
Monthly and annual power sector data were written twice. Once in Step 12 and one in step 18. This is because the monthly and annual data are always written when the `write_power_sector_results`, hourly data are written or not depending on the setting of a boolean parameter named `include_hourly`. We use the same behavior for monthly and annual.
Also, add CPLW to `BA_930_INCONSISTENCY` dictionary.
Advances CAR-4691
Add the `include_monthly` and `include_annual` parameters to the `write_power_sector_results` function and use `if`/`else` logic to write or not data.
Ran the pipeline for 2023
* the `write_power_sector_results` function in the `oge.output_data` module and the pipeline where this function is called
* the updated `BA_930_INCONSISTENCY` dictionary where CPLW has been added for …
> Refactor function writing power sector data

- src/oge/output_data.py
This PR addresses https://github.com/singularity-energy/open-grid-emissions/issues/309 by adding some of the data from the plant attributes table to the annual plant data table to make it easier to filter and explore in spreadsheet form without having to use code to merge in the plant attributes table. 
Advances CAR-4691
See above
Running pipeline
5 minutes
What issues were identified that are not being addressed in this PR but should be addressed in future work?
> Add plant attributes to the plant_data file

- src/oge/data_cleaning.py
- src/oge/data_pipeline.py
- src/oge/gross_to_net_generation.py
- src/oge/helpers.py
- src/oge/output_data.py
This PR adds a new subplant attributes table to results/plants data that contains subplant-specific attributes including:
- subplant primary fuel
- Fuel category
- Nameplate capacity
- Primary prime mover
This PR also moves the code introduced in https://github.com/singularity-energy/open-grid-emissions/pull/403/commits/d7b63680e6dcf5f5a6448875a512dd2fc6909738 from the `helpers.assign_fleet_to_subplant_data` function into the `data_cleaning.aggregate_subplant_data_to_fleet` function.
Advances CAR-4691
Had to rearrange some functions to avoid circular imports
Running 2023 data pipeline
10 min
Maybe add more fields to this table
> Add subplant attributes table

- CITATION.cff
- Pipfile.lock
- README.md
- pyproject.toml
- src/oge/constants.py
- src/oge/data_pipeline.py
- src/oge/download_data.py
- src/oge/eia930.py
- src/oge/helpers.py
- src/oge/output_data.py
- src/oge/validation.py
- src/oge/visualization.py
Final cleanup before the 2023 data release, including various small fixes: 
- bump the version to 0.6.0 
- Update the pipfile.lock to address security warnings
- Add handling for geopy timeout errors: when using geopy to lookup missing lat/long or city/state/county, sometimes the request times out or the geocoder is unavailable. Previously this was causing the entire pipeline to crash. This adds a retry loop to retry the request once if unsuccessful, as well as handling both errors and returning nans if it fails twice. 
- Fixes a bug that introduced duplicate columns in the plant_data output file. 
- Fixes a bug where the `downloads/eia923` directory was not being created if the year was < 2008 and the directory did not already exist
- For years prior to 2019, outputs the …
> Final Cleanup
